#!/bin/bash -x

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

# Prepare database initialization
cat <<EOF > restore/zz_stop.sh
#!/bin/sh
# stop the container
exit 1
EOF
chmod a+x restore/zz_stop.sh

# Execute database restore
# The cointainer will be stopped at the end
/usr/bin/podman run --rm --replace --name postgres-app --env-file=$HOME/.config/state/environment \
    --volume postgres-data:/var/lib/postgresql/data:Z \
    --env POSTGRES_USER=odoouser \
    --env POSTGRES_PASSWORD=ZhuMeYvgByyf \
    --env POSTGRES_DB=odoo \
    --env TZ=UTC \
    ${POSTGRES_IMAGE}

# Cleanup database data
rm -f restore/zz_stop.sh restore/dump.sql

# Start services
systemctl --user start odoo

# Wait a bit for container initialization
sleep 10


# Wait for the container
while ! podman ps | grep -q odoo
do
    echo "Waiting for odoo"
    sleep 1
done

# Wait a bit for container initialization
sleep 5
