#!/usr/bin/env python3

import os
import traceback
import requests

BASE_URL = "https://ns8-odoo-track.innovyou.cloud"

# track create module

try:
    req = requests.post(
        "%s/track-download.php" % (
            BASE_URL
        ),
        json = {}
    )
    print("Request ok!")
except Exception as ex:
    print("Error during track download post request: ", traceback.format_exc())