version: '3'
services:
    db:
        container_name: "odoo16-dev-postgres"
        image: postgres:15.2
        environment:
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
            - POSTGRES_DB=postgres
        volumes:
            - ./postgres-data:/var/lib/postgresql/data

    odoo:
        container_name: "odoo16-dev-odoo"
        build:
            context: ./build
            dockerfile: ../Dockerfile.example
        depends_on:
            - db
        ports:
            - "8069:8069"
            - "8071:8071"
            - "8072:8072"
            - "8888:8888"
        volumes:
            - ./odoo-data:/var/lib/odoo
        command:
            - /bin/bash
            - -c
            - |
              /bin/env_to_conf.sh
              /bin/start_odoo.sh
        env_file:
            - ./.env.example
networks:
    odoo_shared:
        name: odoo_network
        external: true
