#!/usr/bin/env python3
import os
import sys
import json
import agent
import agent.tasks

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

# Find default traefik instance for current node
default_traefik_id = agent.resolve_agent_id('traefik@node')
if default_traefik_id is None:
    sys.exit(2)

# Remove traefik route
response = agent.tasks.run(
    agent_id=default_traefik_id,
    action='delete-route',
    data={
        'instance': os.environ['MODULE_ID']
    },
)

# Check if traefik configuration has been successfull
agent.assert_exp(response['exit_code'] == 0)

# Remove traefik route alt
response2 = agent.tasks.run(
    agent_id=default_traefik_id,
    action='delete-route',
    data={
        'instance': "gevent%s" % (os.environ['MODULE_ID'])
    },
)

# Check if traefik configuration has been successfull
agent.assert_exp(response2['exit_code'] == 0)
