#!/usr/bin/env python3

import os
import json
import sys
import agent

# Prepare return variable
config = {}

# Read current configuration from Redis
env = f'module/{os.environ["MODULE_ID"]}/environment'
rdb = agent.redis_connect()

config["host"] =  rdb.hget(env, "TRAEFIK_HOST");
config["http2https"] =  rdb.hget(env, "TRAEFIK_HTTP2HTTPS") == "True";
config["lets_encrypt"] =  rdb.hget(env, "TRAEFIK_LETS_ENCRYPT") == "True";

# Dump the configuratio to stdout
json.dump(config, fp=sys.stdout)
