#!/bin/bash

set -e -o pipefail
exec 1>&2 # Redirect any output to the journal (stderr)

# restore odoo db
echo "Restoring odoo postgres database"
podman exec -i postgres psql -U odoodbuser -d postgres < odoo.pg_dump

