#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e -o pipefail
exec 1>&2 # Redirect any output to the journal (stderr)

# restore odoo db
echo "Restoring odoo postgres database"
podman exec -i postgres psql -U odoodbuser -d postgres < odoo.pg_dump

